# Generated by Django 3.2 on 2021-05-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='age',
            field=models.CharField(help_text='고객님의 나이를 입력해주세요.', max_length=3),
        ),
    ]
