# Generated by Django 3.2 on 2021-05-28 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='phone_number',
            field=models.CharField(help_text='고객님의 전화 번호를 입력해주세요.', max_length=11, validators=[django.core.validators.MinLengthValidator(10, '- 없이 올바른 전화번호를 입력했는지 확인해주세요.'), django.core.validators.MaxLengthValidator(12, '- 없이 올바른 전화번호를 입력했는지 확인해주세요.')]),
        ),
    ]
