# Generated by Django 3.2 on 2021-04-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='status',
        ),
        migrations.AddField(
            model_name='estimate',
            name='purpose_of_estimate',
            field=models.CharField(blank=True, choices=[('a', '수선'), ('l', '세탁'), ('r', '리폼')], default='a', help_text='패피스에 고객님의 소중한 상품을 맡기시는 목적을 선택해주세요.', max_length=1),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='brand',
            field=models.CharField(help_text='고객님의 상품의 브랜드를 입력해주세요', max_length=100),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('b', '가방'), ('t', '바지'), ('s', '신발')], default='b', help_text='고객님의 상품의 종류를 선택해주세요', max_length=1),
        ),
    ]
