# Generated by Django 3.2 on 2021-04-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20210416_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='update_date',
            new_name='create_date',
        ),
    ]
