# Generated by Django 3.2 on 2021-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_estimate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
