# Generated by Django 3.2 on 2021-04-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_rename_update_date_estimate_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='photo',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('request_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.request')),
            ],
        ),
    ]
