# Generated by Django 3.2 on 2021-06-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_estimate_is_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='DetailImage',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='overall_image',
        ),
        migrations.AddField(
            model_name='estimate',
            name='brand',
            field=models.TextField(default='상품 브랜드', max_length=20),
        ),
        migrations.AddField(
            model_name='estimate',
            name='price',
            field=models.TextField(default='상품 구입 가격', max_length=20),
        ),
        migrations.AddField(
            model_name='estimate',
            name='year',
            field=models.TextField(default='상품 구입 연도', max_length=20),
        ),
        migrations.CreateModel(
            name='OverallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_image', models.ImageField(upload_to='overall-image/')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.estimate')),
            ],
        ),
    ]
