# Generated by Django 3.2 on 2021-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20210602_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='brand',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='price',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='year',
            field=models.TextField(max_length=20),
        ),
    ]
