# Generated by Django 3.2 on 2021-04-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_estimate_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='author',
        ),
    ]
