# Generated by Django 3.2 on 2021-06-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20210603_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='age',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='gender',
        ),
    ]
