# Generated by Django 3.2 on 2021-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_auto_20210615_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='brand',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='price',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='year',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
