# Generated by Django 3.2 on 2021-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_remove_estimate_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='brand',
        ),
        migrations.AddField(
            model_name='estimate',
            name='address',
            field=models.TextField(default='배송을 받기 위한 고객님의 주소를 입력해주세요.', help_text='고객님의 주소를 입력해주세요.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='age',
            field=models.IntegerField(default=20, help_text='고객님의 나이를 입력해주세요.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='gender',
            field=models.CharField(blank=True, choices=[('a', '가방/핸드백'), ('b', '아우터'), ('c', '상의'), ('d', '하의'), ('e', '신발'), ('f', '지갑/벨트'), ('g', '패션 잡화'), ('h', '기타')], default='m', help_text='고객님의 성별을 선택해주세요', max_length=1),
        ),
        migrations.AddField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='이름', help_text='고객님의 이름을 입력해주세요.', max_length=10),
        ),
        migrations.AddField(
            model_name='estimate',
            name='phone_number',
            field=models.CharField(default='01000000000', help_text='고객님의 전화 번호를 입력해주세요.', max_length=11),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='type_of_product',
            field=models.CharField(blank=True, choices=[('a', '가방/핸드백'), ('b', '아우터'), ('c', '상의'), ('d', '하의'), ('e', '신발'), ('f', '지갑/벨트'), ('g', '패션 잡화'), ('h', '기타')], default='a', help_text='고객님의 상품의 종류를 선택해주세요', max_length=1),
        ),
    ]
