# Generated by Django 3.2 on 2021-04-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_auto_20210428_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='request_target',
        ),
        migrations.AddField(
            model_name='estimate',
            name='request_content',
            field=models.TextField(default='전달하실 요청사항을 자세히 입력해주세요.', max_length=1000),
        ),
        migrations.AddField(
            model_name='photo',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landingpage.estimate'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', '남자'), ('f', '여자')], default='m', help_text='고객님의 성별을 선택해주세요', max_length=1),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
