# Generated by Django 3.2 on 2021-04-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_auto_20210428_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='address',
            field=models.TextField(help_text='고객님의 주소를 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='age',
            field=models.IntegerField(help_text='고객님의 나이를 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(help_text='고객님의 이름을 입력해주세요.', max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='phone_number',
            field=models.CharField(help_text='고객님의 전화 번호를 입력해주세요.', max_length=11),
        ),
        migrations.AlterField(
            model_name='photo',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.estimate'),
            preserve_default=False,
        ),
    ]
