# Generated by Django 3.2 on 2021-07-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_rename_email_sent_estimate_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='is_sent',
        ),
    ]
