# Generated by Django 3.2 on 2021-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_auto_20210428_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='age',
            field=models.IntegerField(default=20, help_text='고객님의 나이를 입력해주세요.'),
        ),
    ]
