# Generated by Django 3.2 on 2021-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_auto_20210428_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='age',
            field=models.IntegerField(default=20, help_text='고객님의 나이를 입력해주세요.'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='purpose_of_estimate',
            field=models.CharField(choices=[('a', '수선'), ('l', '세탁'), ('r', '리폼')], default='a', help_text='패피스에 고객님의 소중한 상품을 맡기시는 목적을 선택해주세요.', max_length=1),
        ),
    ]
