# Generated by Django 3.2 on 2021-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_remove_estimate_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
